redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/vizyzsu/Documents/GitHub/amigos"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/Amigos%20Fooldal%20v2.dc.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/home"
to = "/Amigos%20Fooldal%20v2.dc.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]